name = "superdeli-demo"
main = "workers-site"
compatibility_date = "2026-01-07"

# account_id: opcional si usas `wrangler login`. Si prefieres, añade tu account_id aquí.
# account_id = "TU_ACCOUNT_ID_AQUI"

[site]
bucket = "./public"
entry-point = "workers-site"